services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.python
    container_name: ${PYTHON_CONTAINER_NAME}
    command: make d-cmd
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ..:/app
